"""empty message

Revision ID: 6609668589a9
Revises: 5863d6cb845b
Create Date: 2023-03-30 13:39:11.994108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6609668589a9'
down_revision = '5863d6cb845b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
